# Wave related
show_in_chat_method: "message_reformat" # you can also put instead of 'message_reformat' 'broadcast'
waves:
  gg_wave:
    word: "GG"
    wave-started:
      - "&cWave started"
      - "Type gg for &c500$"
    wave-ended:
      - "The wave has ended!"
      - "&dTest line 2"
    wave-length: 10
    reward-commands: # it will take priority by the following number after tier, e.g. tier{number}, it will follow the {number}
      tier1:
        - "100:msg {player} tier1 gg wave"
        - "20:eco give {player} 500 gg wave"
      tier2:
        - "70:msg {player} tier2 gg wave"
        - "20:eco give {player} 1000 gg wave"
  l_wave:
    word: "L"
    wave-started:
      - "&cWave started"
      - "Type L for &c500$"
    wave-ended:
      - "The L wave has ended!"
      - "&dTest line 2"
    wave-length: 10
    reward-commands: # it will take priority by the following number after tier, e.g. tier{number}, it will follow the {number}
      tier1:
        - "100:msg {player} tier1 L wave"
        - "50:eco give {player} 500 L wave"
      tier2:
        - "100:msg {player} tier2 L wave"
        - "30:eco give {player} 1000 L wave"
permissions: # this is used for reward-commands to register the perms the player can use
  - tier1
  - tier2
message_format: "&k&l| &r{color}&l{playerDisplayName}: {message}" # you can also use {playerName]/{player] -> they only show the name
# ^^^ -> you can also use placeholders e.g. %gradientdisplayname%
reward-colors:
  - "&a"
  - "&b"
  - "&c"
  - "&d"
  - "&e"
  - "&f"
  # - "&#084CFB" only 1.16+
  - "&0"
  - "&1"
  - "&2"
  - "&3"
  - "&4"
  - "&5"
  - "&6"
  - "&7"
  - "&8"
  - "&9"
reward-messages:
  #- "&cYou received something idk what"
  - NONE
# Permissions related
wave-already-active:
  - "&cThe wave is already active!"
wave-reloaded:
  - "&aYML File reloaded succesfully!"
wave-command-started:
  - "&aYou've started a chat wave!"
