name: ToastedChatWave
version: '${project.version}'
main: me.serbob.toastedchatwave.ToastedChatWave
api-version: 1.13
authors: [ Serbob ]
description: A chat wave plugin.
folia-supported: true
commands:
  wave:
    description: Chat wave command.
    aliases:
      - chatwave
permissions:
  wave.start:
    default: op
  wave.reload:
    default: op
